version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: etl_postgres
    environment:
      POSTGRES_DB: etl_db
      POSTGRES_USER: etl_user
      POSTGRES_PASSWORD: etl_pass
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  etl:
    build: ./etl
    container_name: etl_job
    depends_on:
      - postgres

volumes:
  pg_data:
